### ISSUE TITLE
Profiles Page

### ISSUE THREAD

**Issue by rdoubleaid** [AbbeyCodeLtd/Ship#5]
### Tasks

>Raaid

- [ ] set up profile at start
- [ ] profile menu for other users to see (openable upon tapping on profile)
- [ ] profile settings page
- [ ] profile for other users to see (swipeable card)

### Profile Setup

- [ ] FB profile pic (non-changeable for MVP); note that pic changes dynamically as FB PP changes.
- [ ] FB first name
- [ ] Age (inputtable string)
- [ ] [Uni] (for MVP, NO NEED TO INCLUDE)
- [ ] Biography (editable string; NOT GRAPH API LINKED)
- [ ] List of friends (NOT TO BE DISPLAYED TO USER)
- [ ] List of people they've swiped on (NOT TO BE DISPLAYED TO USER)
- [ ] Radio buttons to agree to privacy policy (with link) and terms of service (with link) (NOT GRAPH API LINKED).

### Profile Menu

Menu screen with rectangular boxes each with ; in order, going down.

- [ ] FB Profile Pic
- [ ] First name, age, [Uni (for MVP, NO NEED TO INCLUDE)]
- [ ] Message button (tap to go to Match Chat)
- [ ] Ask to be Shipped (tap to open a pop up of mutual friends; tap on friend and open Ship Chat)
- [ ] Ship (FADED, CANNOT TAP)
- [ ] View Profile (goes to Facebook profile)

(BEYOND MVP, WE NEED TO HAVE INSTAGRAM INTEGRATION (LIKE ON TINDER) + WE NEED TO LOOK INTO HAVING Q&A PROFILE BUILDERS (DEBATABLE))
